logging:
  level:
    root: INFO

spring:
  profiles:
    active: local
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
      discovery:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
